mode = "dark"

accent = "#268bd2"
selection = "#073642"
muted = "#586e75"

background = "#002b36"
dark_background = "#00212b"
darker_background = "#00171f"
lighter_background = "#073642"

foreground = "#839496"
dark_foreground = "#657b83"
light_foreground = "#93a1a1"
bright_foreground = "#eee8d5"

red = "#dc322f"
yellow = "#b58900"
orange = "#cb4b16"
green = "#859900"
cyan = "#2aa198"
blue = "#268bd2"
magenta = "#d33682"
brown = "#6c71c4"

bright_red = "#dc322f"
bright_yellow = "#b58900"
bright_green = "#859900"
bright_cyan = "#2aa198"
bright_blue = "#268bd2"
bright_magenta = "#d33682"
